### ISSUE TITLE
Umumi duzelisler

### ISSUE THREAD

**Issue by samirkarimov** [aliyev1997/PragmatechFoundationProject#4]
- [ ] Numune aldigin saytdaki olculer ve mesafelerle islemeye calis .Bunun ucun lightshot programindan istifade edebilersen olculeri goturebilmek ucun
- [ ] Folder strukturun yoxdur onu duzeltmek lazimdir.Sass fayllari ayri folder css ayri folderde olmalidir
- [ ] html strukturun yaxsidir xosuma geldi. gridden istifade de yaxsidir buna gore diger dediyim hisseleri duzeltsen problemlerinin ekser hissesi hellediler
- [ ] [burda](https://github.com/aliyev1997/PragmatechFoundationProject/pulls) yaratdigim pull-requestlere nezer sal

**Comment by aliyev1997** [comment]
- Olculere bacardigim qeder deqiqlikden gotururem, ola bilsin ekranin menim terefden boyuk olmamasi bele uygunsuzluq yaradib.
- Hamisini yukledim, folder strukturu seliqeli gorunmelidi indi.
-  Men duzu esas Back End e maragim vardi, meqsedimde o idi, ona gore cox motive deyilem Fronta, ona gore de keyfiyyet asagidi.

**Comment by aliyev1997** [comment]
Olculere bacardigim qeder deqiqlikden gotururem, ola bilsin ekranin menim terefden boyuk olmamasi bele uygunsuzluq yaradib.
Hamisini yukledim (sass, grid, imgs), folder strukturu seliqeli gorunmelidi indi.
Men duzu esas Back End e maragim vardi, meqsedimde o idi, ona gore cox motive deyilem Fronta, ona gore de keyfiyyet asagidi.

**Comment by samirkarimov** [comment]
aha indi daha duzenlidi.. ela.. back end maragin da olsa netice etibari ile bu front olmalidi ki sen backi yazasan o menada sebr elemek lazimdir:))
